<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>ros2_test_utils</name>
  <version>0.1.0</version>
  <description>pytest plugin and test helper classes for integration tests of ROS 2 interfaces.</description>
  <maintainer email="d.kroezen@tudelft.nl">Dave Kroezen</maintainer>
  <license>Apache-2.0</license>

  <depend>python3-pytest</depend>
  <depend>rclpy</depend>

  <test_depend>example_interfaces</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
